#from main import 
from bokeh.embed import server_session
import shutil

uploaded_spectra_library = {}

def on_session_created(session_context):
    # If present, this function executes when the server creates a session.
    uploaded_spectra_library[session_context]

def on_session_destroyed(session_context):
    # If present, this function executes when the server closes a session.
    pass

def process_spectrum(attr, old, new):
    global template
    global syn_spectra_library
    spectrumhex = upload.value
    if len(spectrumhex) < 13981013: #10 MiB in base64 5. Set a file size limit
        spectrumdata = base64.b64decode(spectrumhex, validate=True)
        keyword = spectrumdata[0:6].decode()
        input_filename = new
        if len(input_filename) > 44:
            input_filename = new[0:44]
        
        filetype = "unknown"
        if keyword == "SIMPLE": # 2. Validate the file type, don't trust Content-Type header
            filetype = "fits"
        elif keyword[0:5] == "#ASDF":
            filetype = "asdf"
        elif keyword[0:5] == "%YAML":
            yaml.loads
        else:
            filetype = "txt"

        filename = f"file_{datetime.datetime.now().isoformat()}.{filetype}" # 3. Change the filename to something generated by the application. 6. store files... outside of the webroot 
        with open(f"../uploaded/{filename}", "wb") as outfile:
            outfile.write(spectrumdata)

        try:
            spectrum = load_synfits({"file": [f"../uploaded/{filename}"], "descs": "uploaded"})

            syn_spectra_library[input_filename] = spectrum
            if input_filename not in template.options:
                template.options.append(input_filename)
            template.value = input_filename
            os.remove(f"../uploaded/{filename}") # don't clutter the upload directory
            update_data("","","")
        except Exception as exc:
            warning.text = str(exc)
    else:
        warning.text = "File too large"
