import os
import numpy as np
import synphot as syn
from astropy import units as u
from synphot.models import Empirical1D, ConstFlux1D

relpath=f"{'/'.join(__file__.split('/')[:-1])}/planets"
relpath2=f"{'/'.join(__file__.split('/')[:-1])}/star_galaxy"

def load_solar(filename, label, planetary_radius=None, semimajor_axis=None, skiprows=0):
    planet = {}
    fn = filename
    fn = os.path.join(relpath, fn)
    model = np.loadtxt(fn, skiprows=skiprows)
    lamhr_ = model[:,0]
    Fhr_ = model[:,3]
    solhr_ = model[:,2]
    Ahr_ = (Fhr_/solhr_) 
    lamhr_ = lamhr_[::-1]
    Ahr_ = Ahr_[::-1]

    spec = syn.spectrum.SpectralElement(Empirical1D, points=lamhr_<<u.micron, lookup_table=Ahr_)

    planet["spectrum"] = spec
    planet["Label"] = label
    planet["planetary_radius"] = planetary_radius
    planet["semimajor_axis"] = semimajor_axis

    return planet

def load_normal(filename, label, planetary_radius=None, semimajor_axis=None, skiprows=0, angstroms=False, mult=1.0, lamhr_idx=0, Ahr_idx=1, magV=10, stellar_radius=1, stargalaxy=False):
    planet = {}
    fn = filename
    if stargalaxy:
        fn = os.path.join(relpath2, fn)
    else:
        fn = os.path.join(relpath, fn)
    model = np.loadtxt(fn, skiprows=skiprows)
    lamhr_ = model[:,lamhr_idx]
    Ahr_ = model[:,Ahr_idx] * mult
    if angstroms:
        lamhr_ /= 10000.

    if stargalaxy:
        spec = syn.spectrum.SourceSpectrum(Empirical1D, points=lamhr_<<u.micron, lookup_table=Ahr_<<u.erg/u.s/u.cm**2/u.AA)
    else:
        spec = syn.spectrum.SpectralElement(Empirical1D, points=lamhr_<<u.micron, lookup_table=Ahr_<<u.dimensionless_unscaled)

    planet["spectrum"] = spec
    planet["Label"] = label
    if stargalaxy: # store the luminosity
        planet["magV"] = magV
        planet["stellar_radius"] = stellar_radius
    else:
        planet["planetary_radius"] = planetary_radius
        planet["semimajor_axis"] = semimajor_axis

    return planet

def load_catalog():

    catalog_planet = {}
    catalog_star = {}

    planet = {}
    fn = 'earth_quadrature_radiance_refl.dat'
    fn = os.path.join(relpath, fn)
    model = np.loadtxt(fn, skiprows=8)
    lamhr_ = model[:,0]
    radhr_ = model[:,1]
    solhr_ = model[:,2]
    Ahr_   = np.pi*(np.pi*radhr_/solhr_)
    
    spec = syn.spectrum.SpectralElement(Empirical1D, points=model[:,0]<<u.micron, lookup_table=Ahr_)

    planet["Label"] = 'Synthetic spectrum generated by T. Robinson (Robinson et al. 2011)'
    planet["spectrum"] = spec
    planet["planetary_radius"] = 6400
    planet["semimajor_axis"] = 1


    catalog_planet["Earth"] = planet


    catalog_planet["Venus"]                         = load_solar('new_venus.txt', 'Synthetic spectrum generated by G. Arney', planetary_radius = 6050, semimajor_axis=0.72)

    catalog_planet["Archean Earth"]                 = load_normal("ArcheanEarth_geo_albedo.txt",  'Synthetic spectrum generated by G. Arney (Arney et al. 2016)', planetary_radius = 6400, semimajor_axis=1, skiprows=8)
    catalog_planet["Hazy Archean Earth"]            = load_normal("Hazy_ArcheanEarth_geo_albedo.txt", 'Synthetic spectrum generated by G. Arney (Arney et al. 2016)',  planetary_radius = 6400, semimajor_axis=1, skiprows=8)
    catalog_planet["1% PAL O2 Proterozoic Earth"]   = load_normal('proterozoic_hi_o2_geo_albedo.txt',  'Synthetic spectrum generated by G. Arney (Arney et al. 2016)', planetary_radius = 6400, semimajor_axis=1)
    catalog_planet['0.1% PAL O2 Proterozoic Earth'] = load_normal('proterozoic_low_o2_geo_albedo.txt', 'Synthetic spectrum generated by G. Arney (Arney et al. 2016)', planetary_radius = 6400, semimajor_axis=1)
    catalog_planet['Early Mars']                    = load_normal('EarlyMars_geo_albedo_trimmed.txt', 'Synthetic spectrum generated by G. Arney based on Smith et al. 2014', planetary_radius = 3400, semimajor_axis=1.52, skiprows=0)
    catalog_planet['Mars']                          = load_normal('Mars_geo_albedo.txt', 'Synthetic spectrum generated by T. Robinson', planetary_radius = 3400, semimajor_axis=1.52, skiprows=8)
    catalog_planet['Jupiter']                       = load_normal('Jupiter_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)', planetary_radius = 70000, semimajor_axis=5.2)
    catalog_planet['Saturn']                        = load_normal('Saturn_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)', planetary_radius = 58200, semimajor_axis=9.58)
    catalog_planet['Uranus']                        = load_normal('Uranus_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)', planetary_radius = 25300, semimajor_axis=19.2)
    catalog_planet['Neptune']                       = load_normal('Neptune_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)', planetary_radius = 24600, semimajor_axis=30.1)

    catalog_planet['Warm Neptune at 2 AU']            = load_normal('Reflection_a2_m1.txt', 'Synthetic spectrum generated by R. Hu (Hu and Seager 2014)', planetary_radius = 24600, semimajor_axis=2.0, angstroms=True, mult=0.67)
    catalog_planet['Warm Neptune w/o Clouds at 1 AU'] = load_normal('Reflection_a1_m2.6_LM_NoCloud.txt', 'Synthetic spectrum generated by R. Hu (Hu and Seager 2014)', planetary_radius = 24600, semimajor_axis=1, angstroms=True, mult=0.67)
    catalog_planet['Warm Neptune w/ Clouds at 1 AU']  = load_normal('Reflection_a1_m2.6_LM.txt', 'Synthetic spectrum generated by R. Hu', planetary_radius = 24600, semimajor_axis=1, angstroms=True, mult=0.67)
    catalog_planet['Warm Jupiter at 0.8 AU']          = load_normal('0.8AU_3x.txt', 'Synthetic spectrum generated by K. Cahoy (Cahoy et al. 2010)', planetary_radius = 70000, semimajor_axis=0.8, skiprows=1, lamhr_idx=1, Ahr_idx=3)
    catalog_planet['Warm Jupiter at 2 AU']            = load_normal('2AU_3x.txt', 'Synthetic spectrum generated by K. Cahoy (Cahoy et al. 2010)', planetary_radius = 70000, semimajor_axis=2, skiprows=1, lamhr_idx=1, Ahr_idx=3)         
    catalog_planet['False O2 Planet (orbiting F2V)']  = load_normal('fstarcloudy_geo_albedo.txt', 'Synthetic spectrum generated by S. Domagal-Goldman (Domagal-Goldman et al. 2014)', planetary_radius = 10000, semimajor_axis=1)

    catalog_planet['Proxima Cen b 10 bar 95% O2 dry'] = load_solar('Proxima15_o2lb_10bar_dry.pt_filtered_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b 10 bar 95% O2 wet'] = load_solar('Proxima15_o2lb_10bar_h2o.pt_filtered_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b 10 bar O2-CO2']     = load_solar('Proxima16_O2_CO2_10bar_prox_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b 90 bar O2-CO2']     = load_solar('Proxima16_O2_CO2_90bar_prox_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b 90 bar Venus']      = load_solar('Proxima17_smart_spectra_Venus90bar_clouds_500_100000cm-1_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b 10 bar Venus']      = load_solar('Proxima17_smart_spectra_Venus10bar_cloudy_500_100000cm-1_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b CO2/CO/O2 dry']     = load_solar('Proxima18_gao_toa.rad', 'Synthetic spectrum generated by E. Schwieterman based on work by P. Gao (Meadows et al. 2016; Gao et al. 2015)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)

    planet = {}

    # this one needs a weighted average
    fn = 'Proxima19_earth_prox.pt_stratocum_hitran2012_50_100000cm_toa.rad'
    fn1 = 'Proxima19_earth_prox.pt_filtered_hitran2012_50_100000cm_toa.rad'
    fn2 = 'Proxima19_earth_prox.pt_stratocum_hitran2012_50_100000cm_toa.rad'
    fn = os.path.join(relpath, fn)
    fn1 = os.path.join(relpath, fn1)
    fn2 = os.path.join(relpath, fn2)
    model = np.loadtxt(fn, skiprows=1)
    lamhr_ = model[:,0]
    solhr_ = model[:,2]
    Flx_ = model[:,3]
    model1 = np.loadtxt(fn1, skiprows=1)
    lamhr_1 = model1[:,0]
    solhr_1 = model1[:,2]
    Flx_1 = model1[:,3]
    model2 = np.loadtxt(fn2, skiprows=1)
    lamhr_2 = model2[:,0]
    solhr_2 = model2[:,2]
    Flx_2 = model2[:,3]
    Ahr_ = Flx_/solhr_
    Ahr_1 = Flx_1/solhr_1
    Ahr_2 = Flx_2/solhr_2
    Ahr_ = (Ahr_*0.25+Ahr_2*0.25+Ahr_1*0.5)
    lamhr_ = lamhr_[::-1]
    Ahr_ = Ahr_[::-1]

    spec = syn.spectrum.SourceSpectrum(Empirical1D, points=lamhr_<<u.micron, lookup_table=Ahr_)
    planet["spectrum"] = spec
    planet["planetary_radius"] = 7650
    planet["semimajor_axis"] = 0.048
    planet["Label"] = 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)'
    catalog_planet["Proxima Cen b Earth"] = planet

    catalog_planet['Proxima Cen b Archean Earth']      = load_solar('Proxima21_HAZE_msun21_0.0Ga_1.00e-02ch4_rmix_5.0E-2__30.66fscale_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
    catalog_planet['Proxima Cen b hazy Archean Earth'] = load_solar('Proxima21_HAZE_msun21_0.0Ga_3.00e-02ch4_rmix_5.0E-2__30.66fscale_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', planetary_radius = 7650, semimajor_axis=0.048, skiprows=1)
            
    lammin=min(lamhr_)
    if lammin <= 0.2:
        lammin = 0.2
    lammax=3.

    #for now I'm just adding these in like the others to save time on reworkign the code. This will need to be tidied up in future. 
    # All magnitude values come from Eric Mamajek's table, https://www.pas.rochester.edu/%7Eemamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt

    catalog_star["O5V star"]                         = load_normal('pickles_uk_1.ascii',  'Pickles stellar catalog ', magV=-5.8, stellar_radius=11.45, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["B5V star"]                         = load_normal('pickles_uk_6.ascii',  'Pickles stellar catalog ', magV=-0.85, stellar_radius=3.36, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["A0V star"]                         = load_normal('pickles_uk_9.ascii',  'Pickles stellar catalog ', magV=0.99, stellar_radius=2.193, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["A5V star"]                         = load_normal('pickles_uk_12.ascii',  'Pickles stellar catalog ', magV=2.01, stellar_radius=1.785, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["F0V star"]                         = load_normal('pickles_uk_14.ascii',  'Pickles stellar catalog ', magV=2.57, stellar_radius=1.728, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["F5V star"]                         = load_normal('pickles_uk_16.ascii',  'Pickles stellar catalog ', magV=3.37, stellar_radius=1.473, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["G0V star"]                         = load_normal('pickles_uk_23.ascii',  'Pickles stellar catalog ', magV=4.48, stellar_radius=1.100, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["G2V star"]                         = load_normal('pickles_uk_26.ascii',  'Pickles stellar catalog ', magV=4.80, stellar_radius=1.012, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["G5V star"]                         = load_normal('pickles_uk_27.ascii',  'Pickles stellar catalog ', magV=4.98, stellar_radius=0.977, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["G8V star"]                         = load_normal('pickles_uk_30.ascii',  'Pickles stellar catalog ', magV=5.30, stellar_radius=0.914, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["K0V star"]                         = load_normal('pickles_uk_31.ascii',  'Pickles stellar catalog ', magV=5.78, stellar_radius=0.813, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["K2V star"]                         = load_normal('pickles_uk_33.ascii',  'Pickles stellar catalog ', magV=6.07, stellar_radius=0.783, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["K5V star"]                         = load_normal('pickles_uk_36.ascii',  'Pickles stellar catalog ', magV=7.28, stellar_radius=0.701, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["M0V star"]                         = load_normal('pickles_uk_38.ascii',  'Pickles stellar catalog ', magV=8.80, stellar_radius=0.588, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["M2V star"]                         = load_normal('pickles_uk_40.ascii',  'Pickles stellar catalog ', magV=10.21, stellar_radius=0.446, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["M4V star"]                         = load_normal('pickles_uk_43.ascii',  'Pickles stellar catalog ', magV=12.61, stellar_radius=0.274, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["M5V star"]                         = load_normal('pickles_uk_44.ascii',  'Pickles stellar catalog ', magV=14.15, stellar_radius=0.196, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["M6V star"]                         = load_normal('pickles_uk_45.ascii',  'Pickles stellar catalog ', magV=16.23, stellar_radius=0.137, skiprows=39, angstroms=True, stargalaxy=True)
    catalog_star["Proxima Centauri star"]            = load_normal('proxima_cen_sed.txt',  'Andrew Lincowski, Eddie Schwieterman, Giada Arney, and Jacob Lustig-Yaeger', magV=15.60, stellar_radius=0.154, skiprows=25, stargalaxy=True)
    catalog_star['L5 brown dwarf']                   = load_normal('L5_2MASS1821p1414_full_fluxed.txt',  'Looper et al. (2008)', magV=24, stellar_radius=0.0909, skiprows=13, stargalaxy=True)
    catalog_star['L8 brown dwarf']                   = load_normal('L8_SDSS0857p5708_full_fluxed.txt',  'Kirkpatrick et al. (2008) and Burgasser et al. (2010)', magV=23.15, stellar_radius=0.0875, skiprows=13, stargalaxy=True)
    catalog_star['T0 brown dwarf']                   = load_normal('T0_SDSS0837m0000_full_fluxed.txt',  'Kirkpatrick et al. (2008) and Burgasser et al. (2006)', magV=25.5, stellar_radius=0.98, skiprows=13, stargalaxy=True)
    catalog_star['T9 brown dwarf']                   = load_normal('T9_WISE1741p2553_full_fluxed.txt',  'Kirkpatrick et al. (2011)', magV=30, stellar_radius=0.100, skiprows=13, stargalaxy=True)
    #catalog_star['NGC 337 spiral galaxy']            = load_normal('NGC_0337_S_Uv-MIr_bms2014.txt',  'Brown et al. (2014)', magV=12.46, stellar_radius=1.0, skiprows=9, angstroms=True, stargalaxy=True)
    # catalog_star['NGC 660 peculiar galaxy']          = load_normal('NGC_0660_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    # catalog_star['NGC 4621 elliptical galaxy']       = load_normal('NGC_4621_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    # catalog_star['NGC 5033 spiral galaxy']           = load_normal('NGC_5033_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    # catalog_star['Haro 6 blue compact dwarf galaxy'] = load_normal('Haro_06_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    # catalog_star['NGC 7476 spiral galaxy']           = load_normal('NGC_7674_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)

    return catalog_planet, catalog_star
