import os
import numpy as np
import synphot as syn

relpath=f"{__file__}/planets"
relpath2=f"{__file__}/star_galaxy"

def load_solar(filename, label, skiprows=0):
    planet = {}
    fn = filename
    fn = os.path.join(relpath, fn)
    model = np.loadtxt(fn, skiprows=skiprows)
    lamhr_ = model[:,0]
    Fhr_ = model[:,3]
    solhr_ = model[:,2]
    Ahr_ = (Fhr_/solhr_) 
    lamhr_ = lamhr_[::-1]
    Ahr_ = Ahr_[::-1]

    planet["lamhr_"] = lamhr_
    planet["Ahr_"] = Ahr_
    planet["Label"] = label

    return planet

def load_normal(filename, label, skiprows=0, angstroms=False, mult=1.0, lamhr_idx=0, Ahr_idx=1, stargalaxy=False):
    planet = {}
    fn = filename
    if stargalaxy:
        fn = os.path.join(relpath2, fn)
    else:
        fn = os.path.join(relpath, fn)
    model = np.loadtxt(fn, skiprows=skiprows)
    lamhr_ = model[:,lamhr_idx]
    Ahr_ = model[:,Ahr_idx] * mult
    if angstroms:
        lamhr_ /= 1000.

    planet["lamhr_"] = lamhr_
    if stargalaxy: # if true, this is actually a star or galaxy, and the column is flux, not albedo.
        planet["Flx_"] = Ahr_
    else:
        planet["Ahr_"] = Ahr_
    planet["Label"] = label
    return planet

def load_catalog():

    catalog = {}

    planet = {}
    fn = 'earth_quadrature_radiance_refl.dat'
    fn = os.path.join(relpath, fn)
    model = np.loadtxt(fn, skiprows=8)
    lamhr_ = model[:,0]
    radhr_ = model[:,1]
    solhr_ = model[:,2]
    Ahr_   = np.pi*(np.pi*radhr_/solhr_)
    planet["lamhr_"] = model[:,0]
    planet["Ahr_"] = Ahr_
    planet["Label"] = 'Synthetic spectrum generated by T. Robinson (Robinson et al. 2011)'
    catalog["Earth"] = planet


    catalog["Venus"]                         = load_solar('new_venus.txt', 'Synthetic spectrum generated by G. Arney')

    catalog["Archean Earth"]                 = load_normal("ArcheanEarth_geo_albedo.txt",  'Synthetic spectrum generated by G. Arney (Arney et al. 2016)', skiprows=8)
    catalog["Hazy Archean Earth"]            = load_normal("Hazy_ArcheanEarth_geo_albedo.txt", 'Synthetic spectrum generated by G. Arney (Arney et al. 2016)', skiprows=8)
    catalog["1% PAL O2 Proterozoic Earth"]   = load_normal('proterozoic_hi_o2_geo_albedo.txt', "1% PAL O2 Proterozoic Earth", 'Synthetic spectrum generated by G. Arney (Arney et al. 2016)')
    catalog['0.1% PAL O2 Proterozoic Earth'] = load_normal('proterozoic_low_o2_geo_albedo.txt', 'Synthetic spectrum generated by G. Arney (Arney et al. 2016)')
    catalog['Early Mars']                    = load_normal('EarlyMars_geo_albedo.txt', 'Synthetic spectrum generated by G. Arney based on Smith et al. 2014', skiprows=8)
    catalog['Mars']                          = load_normal('Mars_geo_albedo.txt', 'Synthetic spectrum generated by T. Robinson', skiprows=8)
    catalog['Jupiter']                       = load_normal('Jupiter_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)')
    catalog['Saturn']                        = load_normal('Saturn_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)')
    catalog['Uranus']                        = load_normal('Uranus_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)')
    catalog['Neptune']                       = load_normal('Neptune_geo_albedo.txt', '0.9-0.3 microns observed by Karkoschka et al. (1998); 0.9-2.4 microns observed by Rayner et al. (2009)')

    catalog['Warm Neptune at 2 AU']            = load_normal('Reflection_a2_m1.txt', 'Synthetic spectrum generated by R. Hu (Hu and Seager 2014)', angstroms=True, mult=0.67)
    catalog['Warm Neptune w/o Clouds at 1 AU'] = load_normal('Reflection_a1_m2.6_LM_NoCloud.txt', 'Synthetic spectrum generated by R. Hu (Hu and Seager 2014)', angstroms=True, mult=0.67)
    catalog['Warm Neptune w/ Clouds at 1 AU']  = load_normal('Reflection_a1_m2.6_LM.txt', 'Synthetic spectrum generated by R. Hu', angstroms=True, mult=0.67)
    catalog['Warm Jupiter at 0.8 AU']          = load_normal('0.8AU_3x.txt', 'Synthetic spectrum generated by K. Cahoy (Cahoy et al. 2010)', skiprows=1, lamhridx=1, Ahr_idx=3)
    catalog['Warm Jupiter at 2 AU']            = load_normal('2AU_3x.txt', 'Synthetic spectrum generated by K. Cahoy (Cahoy et al. 2010)', skiprows=1, lamhridx=1, Ahr_idx=3)         
    catalog['False O2 Planet (orbiting F2V)']  = load_normal('fstarcloudy_geo_albedo.txt', 'Synthetic spectrum generated by S. Domagal-Goldman (Domagal-Goldman et al. 2014)')

    catalog['Proxima Cen b 10 bar 95% O2 dry'] = load_solar('Proxima15_o2lb_10bar_dry.pt_filtered_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b 10 bar 95% O2 wet'] = load_solar('Proxima15_o2lb_10bar_h2o.pt_filtered_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b 10 bar O2-CO2']     = load_solar('Proxima16_O2_CO2_10bar_prox_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b 90 bar O2-CO2']     = load_solar('Proxima16_O2_CO2_90bar_prox_hitran2012_50_100000cm_toa.rad', 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b 90 bar Venus']      = load_solar('Proxima17_smart_spectra_Venus90bar_clouds_500_100000cm-1_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b 10 bar Venus']      = load_solar('Proxima17_smart_spectra_Venus10bar_cloudy_500_100000cm-1_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b CO2/CO/O2 dry']     = load_solar('Proxima18_gao_toa.rad', 'Synthetic spectrum generated by E. Schwieterman based on work by P. Gao (Meadows et al. 2016; Gao et al. 2015)', skiprows=1)

    planet = {}

    # this one needs a weighted average
    fn = 'Proxima19_earth_prox.pt_stratocum_hitran2012_50_100000cm_toa.rad'
    fn1 = 'Proxima19_earth_prox.pt_filtered_hitran2012_50_100000cm_toa.rad'
    fn2 = 'Proxima19_earth_prox.pt_stratocum_hitran2012_50_100000cm_toa.rad'
    fn = os.path.join(relpath, fn)
    fn1 = os.path.join(relpath, fn1)
    fn2 = os.path.join(relpath, fn2)
    model = np.loadtxt(fn, skiprows=1)
    lamhr_ = model[:,0]
    solhr_ = model[:,2]
    Flx_ = model[:,3]
    model1 = np.loadtxt(fn1, skiprows=1)
    lamhr_1 = model1[:,0]
    solhr_1 = model1[:,2]
    Flx_1 = model1[:,3]
    model2 = np.loadtxt(fn2, skiprows=1)
    lamhr_2 = model2[:,0]
    solhr_2 = model2[:,2]
    Flx_2 = model2[:,3]
    Ahr_ = Flx_/solhr_
    Ahr_1 = Flx_1/solhr_1
    Ahr_2 = Flx_2/solhr_2
    Ahr_ = (Ahr_*0.25+Ahr_2*0.25+Ahr_1*0.5)
    lamhr_ = lamhr_[::-1]
    Ahr_ = Ahr_[::-1]
    planet["lamhr_"] = lamhr_
    planet["Ahr_"] = Ahr_
    planet["Label"] = 'Synthetic spectrum generated by E. Schwieterman (Meadows et al. 2016)'
    catalog["Proxima Cen b Earth"] = planet

    catalog['Proxima Cen b Archean Earth']      = load_solar('Proxima21_HAZE_msun21_0.0Ga_1.00e-02ch4_rmix_5.0E-2__30.66fscale_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', skiprows=1)
    catalog['Proxima Cen b hazy Archean Earth'] = load_solar('Proxima21_HAZE_msun21_0.0Ga_3.00e-02ch4_rmix_5.0E-2__30.66fscale_toa.rad', 'Synthetic spectrum generated by G. Arney (Meadows et al. 2016)', skiprows=1)
            
    lammin=min(lamhr_)
    if lammin <= 0.2:
        lammin = 0.2
    lammax=3.

    #for now I'm just adding these in like the others to save time on reworkign the code. This will need to be tidied up in future. 

    catalog["O5V star"]                         = load_normal('pickles_uk_1.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["B5V star"]                         = load_normal('pickles_uk_6.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["A5V star"]                         = load_normal('pickles_uk_12.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["F5V star"]                         = load_normal('pickles_uk_16.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["G2V star"]                         = load_normal('pickles_uk_16.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["G5V star"]                         = load_normal('pickles_uk_27.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["K2V star"]                         = load_normal('pickles_uk_33.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["K5V star"]                         = load_normal('pickles_uk_36.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["M0V star"]                         = load_normal('pickles_uk_38.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["M2V star"]                         = load_normal('pickles_uk_40.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["M4V star"]                         = load_normal('pickles_uk_43.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["M5V star"]                         = load_normal('pickles_uk_44.ascii',  'Pickles stellar catalog ', skiprows=39, angstroms=True, stargalaxy=True)
    catalog["Proxima Centauri star"]            = load_normal('proxima_cen_sed.txt',  '', skiprows=25, stargalaxy=True)
    catalog['T0 brown dwarf']                   = load_normal('T0_SDSS0837m0000_full_fluxed.txt',  '', skiprows=13, stargalaxy=True)
    catalog['T9 brown dwarf']                   = load_normal('T9_WISE1741p2553_full_fluxed.txt',  '', skiprows=13, stargalaxy=True)
    catalog['L5 brown dwarf']                   = load_normal('L5_2MASS1821p1414_full_fluxed.txt',  '', skiprows=13, stargalaxy=True)
    catalog['L8 brown dwarf']                   = load_normal('L8_SDSS0857p5708_full_fluxed.txt',  '', skiprows=13, stargalaxy=True)
    catalog['NGC 337 spiral galaxy']            = load_normal('NGC_0337_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    catalog['NGC 660 peculiar galaxy']          = load_normal('NGC_0660_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    catalog['NGC 4621 elliptical galaxy']       = load_normal('NGC_4621_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    catalog['NGC 5033 spiral galaxy']           = load_normal('NGC_5033_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    catalog['Haro 6 blue compact dwarf galaxy'] = load_normal('Haro_06_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)
    catalog['NGC 7476 spiral galaxy']           = load_normal('NGC_7674_S_Uv-MIr_bms2014.txt',  '', skiprows=9, angstroms=True, stargalaxy=True)

    return catalog
